[package]
name = "eq3-max-cube_rs-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eq3-max-cube_rs ={ path = "../"}
tokio ={ version = "1", features = ["full"]}
